[package]
name = "boatbomber/editableimageblur"
description = "Fast blurring for Roblox EditableImage"
version = "0.3.1"
license = "MPL 2.0"
authors = ["boatbomber (https://boatbomber.com)"]
registry = "https://github.com/upliftgames/wally-index"
realm = "shared"
include = ["src", "src/**", "wally.toml", "wally.lock", "default.project.json"]
exclude = ["**"]
